name: Update Hagezi wildcard list (strip *)

on:
  schedule:
    # 每天 03:00 UTC 執行（台灣時間 UTC+8 約 11:00）
    - cron: "0 3 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch and transform
        run: |
          set -euo pipefail

          URL="https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/ultimate.txt"
          mkdir -p output

          # 下載（自動重試，避免臨時網路抖動）
          curl -fsSL --retry 5 --retry-delay 3 "$URL" -o /tmp/ultimate.txt

          # 轉換：
          # 1) 把每行開頭的 "*" 或 "*." 去掉
          # 2) 保留註解與空行（如果你想去除註解，下面有可選做法）
          sed -E 's/^\*\.*//' /tmp/ultimate.txt > output/ultimate.txt

          # 可選：去除 Windows CRLF
          sed -i 's/\r$//' output/ultimate.txt

      - name: Commit changes (if any)
        run: |
          set -e
          if ! git diff --quiet -- output/ultimate.txt; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add output/ultimate.txt
            git commit -m "chore: update ultimate.txt (strip leading *)"
            git push
          else
            echo "No changes."
          fi
