name: Cron Ping
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event=${{ github.event_name }}"
          echo "utc=$(date -u)"
