name: Update Hagezi wildcard list (strip *)

on:
  schedule:
    - cron: '10,25,40,55 * * * *'
  
  workflow_dispatch: {}

  push:
    branches: [ main ]
    paths:
      - '.github/workflows/main.yml'
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch and transform
        run: |
          set -euo pipefail

          URL="https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/ultimate.txt"
          mkdir -p output

          # 下載（自動重試，避免臨時網路抖動）
          curl -fsSL --retry 5 --retry-delay 3 "$URL" -o /tmp/ultimate.txt

          # 轉換：
          # 1) 把每行開頭的 "*" 去掉
          # 2) 保留註解與空行（如果你想去除註解，下面有可選做法）
          sed -E 's/^\*//' /tmp/ultimate.txt > output/ultimate.txt
          sed -i 's/\r$//' output/ultimate.txt

      - name: Commit changes (if any)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 只加入我們輸出的檔案
          git add output/ultimate.txt

          # 檢查「已暫存」的變更（包含新檔）
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update ultimate.txt (strip leading *)"
            git push
          fi
